# Generated by Django 2.1.5 on 2019-02-06 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Registration_Date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2019, 2, 6, 17, 42, 49, 279736, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
