# Generated by Django 2.1.5 on 2019-02-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0003_auto_20190206_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='DOD',
            field=models.DateField(blank=True, null=True, verbose_name='Died'),
        ),
    ]
